; What every track define means while the custom music's sound driver is
; resident. Regenerated by the editor beside custom-music.asm from each
; import: the driver's request sites speak AddmusicK's numbering, so each
; stock track define is redefined to the value the tool gives its song, and
; each imported song gets a track define of its own.
;
; This shipped copy redefines nothing, deliberately. A build with the
; feature on and nothing imported carries no driver, so the stock engine
; answers the mailbox and the stock numbering is the true one.
