; Which songs this project carries, and the sample pool they share: the whole
; of what the custom music feature assembles into the music banks
; Config/MusicBank.asm reserves. Only read under !Define_SMW_CustomMusic.
;
; Regenerated by the editor from one run of AddmusicK, which compiled every
; blob named here. The driver and the sequences have to come from the same
; run: a sequence's place in the sound chip's memory is computed from the
; driver's length, so two runs disagree about where a song lives without
; saying so.
;
; This shipped copy carries nothing, deliberately. A build with the feature
; on and nothing imported places no blob, carries no driver, and runs the
; stock engine over exactly what the stock cartridge plays.

!Define_SMW_CustomMusic_SongCount #= $00
!Define_SMW_CustomMusic_GlobalCount #= $00
!Define_SMW_CustomMusic_ARAMRet #= $0000
!Define_SMW_CustomMusic_ARAMRetMore #= $0000
!Define_SMW_CustomMusic_ARAMRetTable #= $0000

; The driver, and the terminator that closes its stream and names the entry
; point the sound chip jumps to once it has arrived. No run has compiled
; one, so there is nothing to place.
macro SMW_CustomMusic_Driver()
endmacro

macro SMW_CustomMusic_SongPointers()
endmacro

macro SMW_CustomMusic_SamplePointers()
endmacro

macro SMW_CustomMusic_SampleLoops()
endmacro

macro SMW_CustomMusic_SampleGroups()
endmacro

macro SMW_CustomMusic_Blobs()
endmacro
