includeonce

;#############################################################################################################
;# Custom music: songs a project imported, with samples of their own.
;#
;# The stock game's audio is three banks over one window of the SPC700's
;# memory, and every one of them was assembled with the cartridge: a level
;# music value picks a row of a pointer table that only exists while the level
;# bank happens to be resident, and the samples every song plays are one fixed
;# set uploaded once at boot. Nothing there can carry a song somebody wrote
;# afterwards, because there is no room in the window for it and no way to give
;# it a waveform the shipped set does not hold.
;#
;# Setting !Define_SMW_CustomMusic to !TRUE gives the other answer, the one the
;# community's own toolchain settled on: a sound driver that uploads a song and
;# the samples that song needs, together, when the song is asked for. The
;# driver is AddmusicK's, the songs are compiled by AddmusicK, and neither is
;# assembled here -- the editor runs the user's own copy of the tool and writes
;# what it produced into SPC700/Custom/, which this file assembles into the
;# music banks (Config/MusicBank.asm).
;#
;# **Everything is incbin, including the driver.** What AddmusicK emits for a
;# song is already the SPC700's own upload format -- a length, an ARAM
;# destination, and the payload, which is what %SPCDataBlockStart emits -- so a
;# song is a blob to place, not a source to assemble, and the same is true of
;# the driver program itself. That is not only less work: a song's position in
;# ARAM is computed from the driver's size, so the two have to come from one
;# run of the tool, and taking both as blobs from that run is what makes a
;# mismatch impossible rather than merely unlikely.
;#
;# **The stock audio stays exactly where it is.** This feature adds banks and a
;# second uploader; it moves no byte of Engine.asm, the three music banks or
;# the samples, and a build with the define off assembles the cartridge the
;# five releases ship. A build with it on still carries them -- the sound
;# effects are the stock engine's and the game asks for them by the same
;# mailbox -- so what the define adds is a way to reach songs the window never
;# had room for, not a replacement for what is there.
;#
;# The define needs a cartridge assembled at 1 MB or larger, which the banks'
;# reservation says rather than letting the image quietly double.
;#############################################################################################################

; Off unless a build asks for it, guarded so --define wins:
; --define Define_SMW_CustomMusic=1 turns the custom music on.
if defined("Define_SMW_CustomMusic") == 0
	!Define_SMW_CustomMusic = !FALSE
endif

; What the project has, and what the driver blob decided. Regenerated by the
; editor beside the blobs it names; the shipped copy carries no songs, so a
; build with the feature on and nothing imported assembles the tables empty.
if !Define_SMW_CustomMusic == !TRUE
	incsrc "SPC700/Custom/custom-music.asm"
endif

;#############################################################################################################
;# Where it goes: the music banks' head, in one sequence -- the tables,
;# then every blob they point into. Of the four tables only SampleGroups
;# is read today, by symbol, from the patch rewrite; the song and sample
;# pointer tables and the loops ride along unread, because the driver's
;# own runtime carries its own copies of them -- kept for a hand uploader
;# that would want data the runtime does not carry. Nothing declares an
;# address inside the run -- that is what lets the run itself sit above
;# the graphics banks, which do (Config/MusicBank.asm).
;#############################################################################################################

; Place the driver, the tables and the blobs. Called from %SMW_PlaceMusicBanks
; once every bank has emitted.
macro SMW_PlaceCustomMusic()
if !Define_SMW_CustomMusic == !TRUE
	; The frame hook's landing, and the whole of what this feature puts in
	; the game's own path. Five bytes: an RTL and the room for a call, so a
	; cartridge assembled without the sound driver's patch runs a routine
	; that returns and nothing else.
	;
	; **The driver's runtime is not assembled here.** It is AddmusicK's, and
	; the editor writes it in afterwards by assembling that tool's own
	; generated patch -- rewritten to read the data below by symbol rather
	; than place its own, and to enter through this slot rather than hijack
	; the main loop, which is five bytes another feature already wants
	; (Config/GlobalCode.asm). What lands here is a JSL to the driver's frame
	; routine and the RTL after it.
	;
	; Spelled out rather than left to the namespace below, like every other
	; routine under Config/: the label is what the call graph is keyed on.
SMW_CustomMusic_FrameHook:
	RTL					;> Overwritten by the patch's JSL, whose own RTL follows
	NOP
	NOP
	NOP
	NOP

namespace SMW_CustomMusic
	; The driver: one upload block as AddmusicK assembled it, and the
	; terminator that closes the stream and names the entry point. The
	; terminator is ours because the tool's own inserter writes it from the
	; SNES side rather than into the blob.
Driver:
	%SMW_CustomMusic_Driver()

	; One long pointer per music value, then the sample pool's own two, then
	; which samples each song wants. Every row of every one of them is
	; written by the editor: a value with no song holds zero, and the
	; uploader reads that as nothing to do.
SongPointers:
	%SMW_CustomMusic_SongPointers()
SamplePointers:
	%SMW_CustomMusic_SamplePointers()
SampleLoops:
	%SMW_CustomMusic_SampleLoops()
SampleGroups:
	%SMW_CustomMusic_SampleGroups()

	; The blobs: each song's sequence and each sample's waveform, in the
	; order the tables above name them.
Blobs:
	%SMW_CustomMusic_Blobs()
namespace off
endif
endmacro

;#############################################################################################################
;# The uploader is AddmusicK's own runtime, written in over a built cartridge
;# as the build's last pass -- its generated patch, rewritten to read the data
;# above by symbol and to enter through the frame hook slot rather than take
;# the main loop's bytes. It uploads the driver and the global jingles at
;# boot, and a song's samples and sequence when its value is asked for; the
;# three ARAM return addresses the fragment carries are what its transfers
;# resume through.
;#
;# With the driver resident the stock engine never runs, so the forty stock
;# songs ride along in the fragment as AddmusicK's music/originals, at the
;# values its own numbering gives them -- which is why the generated
;# custom-tracks.asm redefines every track define to that numbering, and why
;# a project's own songs answer from $29 up. A build with the feature on and
;# nothing imported carries no patch, runs the stock engine, and plays
;# exactly what the stock cartridge plays.
;#############################################################################################################
