"""The Layer 1 and sprite pointer tables, as something the editor can remap.

``levels/pointers/layer1.asm`` and ``sprites.asm`` are hop 1 of the three-hop
walk :mod:`smw_tools.levels` describes: one directive per level number in
order, each naming the label above a container's insertion. Unlike the Layer 2
table (:mod:`shiny_mushroom.layer2_table`) they speak a single grammar --
``dl SMW_LEVEL_L1_105`` down one file, ``dw SMW_LEVEL_SP_105`` down the other
-- so a remap does not need a donor line to borrow a spelling from, and both
are :class:`~shiny_mushroom.token_table.TokenTable`\ s: one label token moves
and the file is otherwise byte for byte what it was. That type carries what
that guarantees, including that a level may be pointed at a label **no line
currently names** -- which the shipped tree makes ordinary, since thirty-odd
containers are reached by address rather than by number.

What a label *means* -- which container it makes a level read -- is
:func:`smw_tools.levels.definitions`' business, and validating a remap against
it is the caller's
(:meth:`shiny_mushroom.project.Project.save_level_pointers`).
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass

from shiny_mushroom.hexnum import hexnum
from shiny_mushroom.token_table import TokenTable, TokenTableError
from smw_tools.levels import (
    ADDED_FRAGMENT,
    DELETED_FRAGMENT,
    LAYER_1,
    SPRITE_BANKS_FRAGMENT,
    SPRITES,
    Insertion,
    sprite_bank_rows,
)

#: What the labels of a container the *project* adds start with -- defined by
#: the streams fragment below rather than by the banks, and spelled in the
#: tables without the ``SMW_`` namespace because the fragment assembles
#: outside it.
ADDED_LAYER1_PREFIX = "ShinyLevel_L1_"
ADDED_SPRITE_PREFIX = "ShinyLevel_SP_"

#: The two fragments the managed level banks read
#: (``Config/ManagedLevelMemory.asm``), regenerated into the overlay by the
#: project whenever a container is added, deleted or restored -- shadowing
#: the disassembly's stock copies, which answer "no streams added, none
#: deleted".
STREAMS_FRAGMENT = ADDED_FRAGMENT
DELETIONS_FRAGMENT = DELETED_FRAGMENT

#: The third, read by the managed level banks' sprite-bank stub
#: (``Config/ManagedLevelMemory.asm``): the bank of every level's sprite
#: list, derived from the sprite pointer table and regenerated into the
#: overlay beside the table's own copy whenever a remap writes one -- so the
#: two name the same label in every row, and a build cannot read a list out
#: of one bank that the loader completes with another.
BANKS_FRAGMENT = SPRITE_BANKS_FRAGMENT

#: What an added container may be called: a filename on every platform and a
#: token inside a generated label, which is the stricter of the two.
ADDED_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_]{0,63}$")


def added_labels(names: tuple[str, ...]) -> dict[str, str]:
    """Label -> container for the containers a project adds, on
    :func:`smw_tools.levels.definitions`' terms -- the entries the generated
    fragment will define, said here so the pointer tables and the fragment
    cannot spell them differently."""
    found: dict[str, str] = {}
    for name in names:
        found[ADDED_LAYER1_PREFIX + name] = name
        found[ADDED_SPRITE_PREFIX + name] = name
    return found


def added_insertions(names: Iterable[str]) -> tuple[Insertion, ...]:
    """The added containers' streams as the fragment inserts them, in its
    order: the Layer 1 then the sprite list of each file, files in the order
    given. What :func:`streams_fragment` writes and what the packer is asked
    to place, from one list so the two cannot disagree."""
    found: list[Insertion] = []
    for name in names:
        found.append(Insertion(name, LAYER_1, ADDED_LAYER1_PREFIX + name))
        found.append(Insertion(name, SPRITES, ADDED_SPRITE_PREFIX + name))
    return tuple(found)


_GENERATED = (
    "; Generated by Shiny Mushroom -- do not edit: this file is rewritten\n"
    "; whenever a level file is added, deleted or restored, and hand edits do\n"
    "; not survive. The disassembly's stock copy says what the fragment is.\n"
)


def streams_fragment(names: Iterable[str]) -> str:
    """The added files' fragment: one insertion per added stream, under the
    labels the pointer tables spell, through the same macro the level banks
    use -- packed after the banks' own streams by the managed level banks."""
    parts = [_GENERATED]
    parts.extend(
        f"\t%SMW_InsertLevelData({one.label}, {one.container}, SMW_U, {one.kind})\n"
        for one in added_insertions(names)
    )
    return "".join(parts)


def sprite_banks_fragment(sprite_labels: Iterable[str]) -> str:
    """The sprite-bank table's fragment for the sprite pointer table's
    labels, in level order -- :func:`smw_tools.levels.sprite_bank_rows`
    under the generated header."""
    return _GENERATED + "".join(sprite_bank_rows(sprite_labels))


def deleted_fragment(labels: Iterable[str]) -> str:
    """The deleted streams' fragment: one define per stream label, which
    the insertion macro reads as "insert the empty level here instead"."""
    parts = [_GENERATED]
    parts.extend(f"!SMW_LevelDeleted_{label} = 1\n" for label in labels)
    return "".join(parts)


class LevelPointersError(TokenTableError):
    """A table that could not be read, or an entry it does not have."""


@dataclass(frozen=True)
class StreamTarget:
    """One thing a level's stream can be pointed at: a label as the table
    spells it, and the container the label makes a level read."""

    label: str
    container: str


@dataclass(frozen=True)
class PointerTable(TokenTable):
    """One of the two tables, in the level tables' own vocabulary.

    A :class:`~shiny_mushroom.token_table.TokenTable` whose rows are level
    numbers. The parsing, the rewrite and the guarantee that only the label
    token moves are all that type's; what is here is the naming -- a row is an
    *entry*, its index is a *level*, and a refusal says which level in hex.
    """

    noun = "pointer entry"
    plural = "entries"

    @classmethod
    def _error(cls, message: str) -> LevelPointersError:
        return LevelPointersError(message)

    @property
    def labels(self) -> tuple[str, ...]:
        """These tables speak of labels rather than of tokens."""
        return self.tokens

    def token(self, row: int) -> str:
        if not 0 <= row < len(self.tokens):
            raise self._error(
                f"the pointer table has no entry for level {hexnum(row, 3)}"
            )
        return self.tokens[row]

    def label(self, level: int) -> str:
        """What ``level``'s entry names."""
        return self.token(level)

    def levels_pointing(self, label: str) -> tuple[int, ...]:
        """Every level number whose entry names ``label``, in order."""
        return self.rows_naming(label)
