"""The Layer 1 and sprite pointer tables, as something the editor can remap.

``levels/pointers/layer1.asm`` and ``sprites.asm`` are hop 1 of the three-hop
walk :mod:`smw_tools.levels` describes: one directive per level number in
order, each naming the label above a container's insertion. Unlike the Layer 2
table (:mod:`shiny_mushroom.layer2_table`) they speak a single grammar --
``dl SMW_LEVEL_L1_105`` down one file, ``dw SMW_LEVEL_SP_105`` down the other
-- so a remap does not need a donor line to borrow a spelling from: the one
line that changes keeps its own directive, its whitespace and its trailing
comment, and only the label token moves. That also lets a level be pointed at
a label **no line currently names**, which the shipped tree makes ordinary:
thirty-odd containers are reached by address rather than by number, and
pointing a level at one is precisely what a remap is for.

Like its sibling, this module only ever moves labels inside a fixed-size
table: no stream is created or destroyed, no region is priced, and every
untouched line comes through byte for byte. What a label *means* -- which
container it makes a level read -- is :func:`smw_tools.levels.definitions`'
business, and validating a remap against it is the caller's
(:meth:`shiny_mushroom.project.Project.save_level_pointers`).
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass

from shiny_mushroom.hexnum import hexnum
from smw_tools.levels import (
    ADDED_FRAGMENT,
    DELETED_FRAGMENT,
    LAYER_1,
    SPRITE_BANKS_FRAGMENT,
    SPRITES,
    Insertion,
    sprite_bank_rows,
)

#: One pointer-table entry: the directive with its leading whitespace, the
#: label, and everything after it (the tabs and the level-number comment).
_ENTRY = re.compile(r"^(\s*d[lw]\s+)(\S+)(.*)$")

#: What the labels of a container the *project* adds start with -- defined by
#: the streams fragment below rather than by the banks, and spelled in the
#: tables without the ``SMW_`` namespace because the fragment assembles
#: outside it.
ADDED_LAYER1_PREFIX = "ShinyLevel_L1_"
ADDED_SPRITE_PREFIX = "ShinyLevel_SP_"

#: The two fragments the managed level banks read
#: (``Config/ManagedLevelMemory.asm``), regenerated into the overlay by the
#: project whenever a container is added, deleted or restored -- shadowing
#: the disassembly's stock copies, which answer "no streams added, none
#: deleted".
STREAMS_FRAGMENT = ADDED_FRAGMENT
DELETIONS_FRAGMENT = DELETED_FRAGMENT

#: The third, read by the managed level banks' sprite-bank stub
#: (``Config/ManagedLevelMemory.asm``): the bank of every level's sprite
#: list, derived from the sprite pointer table and regenerated into the
#: overlay beside the table's own copy whenever a remap writes one -- so the
#: two name the same label in every row, and a build cannot read a list out
#: of one bank that the loader completes with another.
BANKS_FRAGMENT = SPRITE_BANKS_FRAGMENT

#: What an added container may be called: a filename on every platform and a
#: token inside a generated label, which is the stricter of the two.
ADDED_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_]{0,63}$")


def added_labels(names: tuple[str, ...]) -> dict[str, str]:
    """Label -> container for the containers a project adds, on
    :func:`smw_tools.levels.definitions`' terms -- the entries the generated
    fragment will define, said here so the pointer tables and the fragment
    cannot spell them differently."""
    found: dict[str, str] = {}
    for name in names:
        found[ADDED_LAYER1_PREFIX + name] = name
        found[ADDED_SPRITE_PREFIX + name] = name
    return found


def added_insertions(names: Iterable[str]) -> tuple[Insertion, ...]:
    """The added containers' streams as the fragment inserts them, in its
    order: the Layer 1 then the sprite list of each file, files in the order
    given. What :func:`streams_fragment` writes and what the packer is asked
    to place, from one list so the two cannot disagree."""
    found: list[Insertion] = []
    for name in names:
        found.append(Insertion(name, LAYER_1, ADDED_LAYER1_PREFIX + name))
        found.append(Insertion(name, SPRITES, ADDED_SPRITE_PREFIX + name))
    return tuple(found)


_GENERATED = (
    "; Generated by Shiny Mushroom -- do not edit: this file is rewritten\n"
    "; whenever a level file is added, deleted or restored, and hand edits do\n"
    "; not survive. The disassembly's stock copy says what the fragment is.\n"
)


def streams_fragment(names: Iterable[str]) -> str:
    """The added files' fragment: one insertion per added stream, under the
    labels the pointer tables spell, through the same macro the level banks
    use -- packed after the banks' own streams by the managed level banks."""
    parts = [_GENERATED]
    parts.extend(
        f"\t%SMW_InsertLevelData({one.label}, {one.container}, SMW_U, {one.kind})\n"
        for one in added_insertions(names)
    )
    return "".join(parts)


def sprite_banks_fragment(sprite_labels: Iterable[str]) -> str:
    """The sprite-bank table's fragment for the sprite pointer table's
    labels, in level order -- :func:`smw_tools.levels.sprite_bank_rows`
    under the generated header."""
    return _GENERATED + "".join(sprite_bank_rows(sprite_labels))


def deleted_fragment(labels: Iterable[str]) -> str:
    """The deleted streams' fragment: one define per stream label, which
    the insertion macro reads as "insert the empty level here instead"."""
    parts = [_GENERATED]
    parts.extend(f"!SMW_LevelDeleted_{label} = 1\n" for label in labels)
    return "".join(parts)


class LevelPointersError(ValueError):
    """A table that could not be read, or an entry it does not have."""


@dataclass(frozen=True)
class StreamTarget:
    """One thing a level's stream can be pointed at: a label as the table
    spells it, and the container the label makes a level read."""

    label: str
    container: str


@dataclass(frozen=True)
class PointerTable:
    """One of the two tables as its lines and as its labels, kept together so
    a rewrite can replace one line without re-deriving the rest.

    ``preamble`` is the header comment above the first entry -- both shipped
    files carry one line of it -- preserved verbatim. From the first entry on,
    every line must *be* an entry: a line that is neither would renumber every
    level below it, because the level number is the entry's position.
    """

    preamble: tuple[str, ...]
    lines: tuple[str, ...]
    labels: tuple[str, ...]

    @classmethod
    def read(cls, text: str) -> PointerTable:
        """Parse a table, refusing any line past the preamble that is not an
        entry."""
        preamble: list[str] = []
        lines: list[str] = []
        labels: list[str] = []
        for number, line in enumerate(text.splitlines()):
            found = _ENTRY.match(line)
            if found is None:
                if lines:
                    raise LevelPointersError(
                        f"line {number + 1} of the pointer table is not a "
                        f"pointer entry: {line.strip()!r}"
                    )
                preamble.append(line)
                continue
            lines.append(line)
            labels.append(found.group(2))
        if not lines:
            raise LevelPointersError("the pointer table has no entries at all")
        return cls(preamble=tuple(preamble), lines=tuple(lines), labels=tuple(labels))

    def text(self) -> str:
        return "\n".join(self.preamble + self.lines) + "\n"

    def label(self, level: int) -> str:
        """What ``level``'s entry names."""
        if not 0 <= level < len(self.labels):
            raise LevelPointersError(
                f"the pointer table has no entry for level {hexnum(level, 3)}"
            )
        return self.labels[level]

    def levels_pointing(self, label: str) -> tuple[int, ...]:
        """Every level number whose entry names ``label``, in order."""
        return tuple(level for level, held in enumerate(self.labels) if held == label)

    def repointed(self, level: int, label: str) -> PointerTable:
        """This table with ``level``'s entry naming ``label``.

        Only the label token moves: the directive is the *table's* -- ``dl``
        down one file and ``dw`` down the other -- and the line keeps its own
        spacing and trailing comment, so the rewritten file differs from the
        original in exactly the label that changed.
        """
        if self.label(level) == label:
            return self
        found = _ENTRY.match(self.lines[level])
        assert found is not None  # every held line parsed on the way in
        lines = list(self.lines)
        lines[level] = f"{found.group(1)}{label}{found.group(3)}"
        labels = list(self.labels)
        labels[level] = label
        return PointerTable(
            preamble=self.preamble, lines=tuple(lines), labels=tuple(labels)
        )
